# External Secrets Operator values for local k3d PoC
# Ref: https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
# Mega prod: ESO + IRSA + AWS Secrets Manager provider
# Local: ESO + Kubernetes provider (reads secrets from secrets-source namespace)

installCRDs: true

replicaCount: 1

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

certController:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
