#!/usr/bin/env bash
# .ai/adapters/kiro/install.sh
# Instala el adapter de Kiro: crea .kiro/steering/*.md con frontmatter correcto
# Idempotente.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

echo "=== Kiro adapter install ==="
mkdir -p "$REPO_ROOT/.kiro/steering"
mkdir -p "$REPO_ROOT/.kiro/hooks"

# product.md — contexto del producto, inclusion: always
cat > "$REPO_ROOT/.kiro/steering/product.md" <<'EOF'
---
inclusion: always
---

# Product: Risk Decision Platform

Technical architecture exploration for Risk Decision Platform.
Real-time fraud detection: 150 TPS, p99 < 300ms.

## PoCs

- poc/java-risk-engine: Clean Architecture, no frameworks
- poc/java-vertx-distributed: 4 Maven modules, layer-as-pod
- poc/vertx-risk-platform: Full Vert.x 5 with all comm patterns
- poc/k8s-local: k3d/OrbStack + full k8s stack

Full context: .ai/context/architecture.md
PoC inventory: .ai/context/poc-inventory.md

## Do not touch

poc/, tests/, cli/, docs/, vault/ — user ownership only.
EOF

echo "  created: $REPO_ROOT/.kiro/steering/product.md"

# tech.md — stack tecnico, inclusion: always
cat > "$REPO_ROOT/.kiro/steering/tech.md" <<'EOF'
---
inclusion: always
---

# Tech Stack

Java 25 LTS, --release 25, virtual threads for blocking I/O.
Vert.x 5.0.12 reactive (non-blocking event loop).
Maven 3.9, Postgres 16, Valkey 8, Redpanda v24.2.4.
OpenTelemetry Java agent 2.x, OpenObserve backend.
k3d/OrbStack, Helm 3, ArgoCD 9.2.4, Argo Rollouts 2.40.5.

Full versions: .ai/context/stack.md

## Non-negotiable

- Java 25 LTS only. Do NOT downgrade to 21 or upgrade to 26.
- Every request must produce trace + log + metric via OTEL.
- correlationId in MDC and response header X-Correlation-Id.
EOF

echo "  created: $REPO_ROOT/.kiro/steering/tech.md"

# structure.md — layout del proyecto, inclusion: fileMatch para Java
cat > "$REPO_ROOT/.kiro/steering/structure.md" <<'EOF'
---
inclusion: fileMatch
filePatterns:
  - "**/*.java"
  - "**/pom.xml"
---

# Project Structure

## Canonical Java layout (all poc/ modules must follow)

domain/{entity,repository,usecase,service,rule}
application/{usecase/<aggregate>,mapper,dto}
infrastructure/{controller,consumer,repository,resilience,time}
config/ cmd/

## Dependency rule

domain/ <- application/ <- infrastructure/ <- config/cmd/

domain/ must NOT import from application/ or infrastructure/ — ever.
Outbound ports: interface in domain/repository/, impl in infrastructure/repository/.

## Naming

- Classes: PascalCase
- Methods/fields: camelCase
- SQL: snake_case
- Files: PascalCase.java

See: .ai/primitives/rules/naming-conventions.md
See: .ai/primitives/rules/architecture-clean.md
EOF

echo "  created: $REPO_ROOT/.kiro/steering/structure.md"

echo ""
echo "Kiro adapter installed."
echo "Steering files: $REPO_ROOT/.kiro/steering/"
echo "Open $REPO_ROOT in Kiro to use."
echo "Note: .kiro/specs/ is generated by Kiro IDE — do not create manually."
