#!/usr/bin/env bash
# test-all-report.sh — Regenerate summary.md from an existing test-all run directory.
# Usage:
#   ./scripts/test-all-report.sh                        # regenerate for latest run
#   ./scripts/test-all-report.sh out/test-all/2026-05-07T18-30-00
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_BASE="$PROJECT_ROOT/out/test-all"

TARGET="${1:-$OUT_BASE/latest}"

# Resolve symlink if needed
if [[ -L "$TARGET" ]]; then
  TARGET="$(readlink "$TARGET")"
  # Handle relative symlink
  if [[ "$TARGET" != /* ]]; then
    TARGET="$OUT_BASE/$TARGET"
  fi
fi

if [[ ! -d "$TARGET" ]]; then
  echo "ERROR: directory not found: $TARGET" >&2
  echo "Usage: $0 [out/test-all/<timestamp>]" >&2
  exit 1
fi

echo "Regenerating report for: $TARGET"

# ---------------------------------------------------------------------------
# Re-read results from stored exit-code files
# ---------------------------------------------------------------------------
result_ids=()
result_status=()
result_duration=()
result_note=()

pass_count=0
fail_count=0
skip_count=0
total_dur_s=0

for suite_dir in "$TARGET"/*/; do
  [[ -d "$suite_dir" ]] || continue
  suite_id="$(basename "$suite_dir")"

  exit_code_file="$suite_dir/exit-code"
  stdout_log="$suite_dir/stdout.log"

  if [[ ! -f "$exit_code_file" ]]; then
    continue
  fi

  exit_code="$(cat "$exit_code_file")"

  # Determine status
  stdout_first=""
  if [[ -f "$stdout_log" ]]; then
    stdout_first="$(head -1 "$stdout_log" 2>/dev/null || true)"
  fi

  status="FAIL"
  if echo "$stdout_first" | grep -qi "^SKIP"; then
    status="SKIP"
  elif [[ "$exit_code" == "0" ]]; then
    status="PASS"
  fi

  # Duration from stdout: look for "real" or timing lines, otherwise 0
  dur_s="0.0"

  note="${stdout_first:0:80}"

  result_ids+=("$suite_id")
  result_status+=("$status")
  result_duration+=("$dur_s")
  result_note+=("$note")

  case "$status" in
    PASS) pass_count=$((pass_count + 1)) ;;
    FAIL) fail_count=$((fail_count + 1)) ;;
    SKIP) skip_count=$((skip_count + 1)) ;;
  esac
done

if [[ ${#result_ids[@]} -eq 0 ]]; then
  echo "No suite results found in $TARGET" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Read meta.json for original run metadata
# ---------------------------------------------------------------------------
run_ts="unknown"
git_sha="unknown"
host_name="unknown"
if [[ -f "$TARGET/meta.json" ]]; then
  run_ts="$(grep '"timestamp"' "$TARGET/meta.json" | sed 's/.*"timestamp": *"\([^"]*\)".*/\1/')"
  git_sha="$(grep '"git_sha"' "$TARGET/meta.json" | sed 's/.*"git_sha": *"\([^"]*\)".*/\1/')"
  host_name="$(grep '"host"' "$TARGET/meta.json" | sed 's/.*"host": *"\([^"]*\)".*/\1/')"
fi

# ---------------------------------------------------------------------------
# Write regenerated summary.md
# ---------------------------------------------------------------------------
{
  echo "# Test Orchestrator Report (regenerated)"
  echo ""
  echo "**Original run:** $run_ts"
  echo "**Host:** $host_name"
  echo "**Git SHA:** $git_sha"
  echo "**Regenerated:** $(date -u "+%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u)"
  echo ""
  echo "## Summary"
  echo ""
  echo "| # | Suite | Status | Notes |"
  echo "|---|-------|--------|-------|"
  local_i=0
  for sid in "${result_ids[@]}"; do
    printf "| %d | %s | %s | %s |\n" \
      "$((local_i+1))" "$sid" "${result_status[$local_i]}" "${result_note[$local_i]}"
    local_i=$((local_i + 1))
  done
  echo ""
  echo "**Total:** ${pass_count} PASS · ${fail_count} FAIL · ${skip_count} SKIP"
  echo ""
  echo "---"
  echo ""
  echo "_Regenerated by scripts/test-all-report.sh_"
} > "$TARGET/summary.md"

echo "Written: $TARGET/summary.md"
echo ""
echo "Summary: ${pass_count} PASS · ${fail_count} FAIL · ${skip_count} SKIP"
