apiVersion: v1
kind: ServiceAccount
metadata:
  name: risk-usecase-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-usecase
spec:
  replicas: 3
  selector:
    matchLabels: { app: risk-usecase }
  template:
    metadata:
      labels: { app: risk-usecase, boundary: usecase }
    spec:
      serviceAccountName: risk-usecase-sa
      containers:
        - name: usecase
          image: local/vertx-risk-platform:dev
          args: ["usecase"]
          ports: [{ containerPort: 8081 }]
          env:
            - name: ALLOWED_SCOPE
              value: repository:rw
